server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
        - id: quick-boot-system
          uri: lb://quick-boot-system
          predicates:
            - Path=/api/system/**,/api/auth/**
          filters:
            # 添加了一个过滤器，用于重写API文档的路径。它捕获了api-docs路径"v3/api-docs"以及后面的路径部分，并将其附加到/stripPos/（仅充当占位符，以满足匹配StripPrefix = 1规则），从而允许网关重定向各服务API文档请求。
            # 添加对api-docs路径的重定向处理
            - name: RewritePath
              args:
                regexp: /api/system/(?<apiDocsPath>v3/api-docs.*)$
                replacement: /stripPos/${apiDocsPath}
            - name: RewritePath
              args:
                regexp: /api/auth/(?<apiDocsPath>v3/api-docs.*)$
                replacement: /stripPos/${apiDocsPath}
            - StripPrefix=1
# 合并 oauth2 到 quick-boot-system 模块 降低服务器资源
#        - id: quick-boot-oauth2
#          uri: lb://quick-boot-oauth2
#          predicates:
#            - Path=/api/auth/**
#          filters:
#            - StripPrefix=1
        - id: quick-boot-online
          uri: lb://quick-boot-online
          predicates:
            - Path=/api/online/**
          filters:
            # 添加对api-docs路径的重定向处理
            - name: RewritePath
              args:
                regexp: /api/online/(?<apiDocsPath>v3/api-docs.*)$
                replacement: /stripPos/${apiDocsPath}
            - StripPrefix=1
        - id: quick-boot-flow
          uri: lb://quick-boot-flow
          predicates:
            - Path=/api/flow/**
          filters:
            # 添加对api-docs路径的重定向处理
            - name: RewritePath
              args:
                regexp: /api/flow/(?<apiDocsPath>v3/api-docs.*)$
                replacement: /stripPos/${apiDocsPath}
            - StripPrefix=1
        - id: quick-boot-jimureport
          uri: lb://quick-boot-jimureport
          predicates:
            - Path=/jmreport/**,/api/jmreport/**
          filters:
            # 添加对api-docs路径的重定向处理
            - name: RewritePath
              args:
                regexp: /api/jmreport/(?<apiDocsPath>v3/api-docs.*)$
                replacement: /${apiDocsPath}
            - name: RewritePath
              args:
                regexp: /jmreport/(?<apiDocsPath>v3/api-docs.*)$
                replacement: /${apiDocsPath}
          #  - StripPrefix=2

knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - quick-boot-gateway

# 忽略认证的地址
ignore:
  url:
    - /favicon.ico
    - /doc.html
    - /api/system/v3/api-docs/**
    - /api/auth/v3/api-docs/**
    # - /api/flow/v3/api-docs/**
    # - /api/online/v3/api-docs/**
    - /webjars/**
    - /swagger-resources/**
    - /v3/api-docs/**
    - /actuator/**
    - /instances/**
    - /api/system/menu/getRoutes
    - /api/auth/doLogin
    - /api/auth/oauth2/**
    - /jmreport/**
    - /api/system/tenant/list