server:
  port: 9999

spring:
  cloud:
    gateway:
      routes:
        - id: quick-boot-system
          uri: lb://quick-boot-system
          predicates:
            - Path=/api/system/**
          filters:
            - StripPrefix=2
        - id: quick-boot-oauth2
          uri: lb://quick-boot-oauth2
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: quick-boot-online
          uri: lb://quick-boot-online
          predicates:
            - Path=/api/online/**
          filters:
            - StripPrefix=2
        - id: quick-boot-jimureport
          uri: lb://quick-boot-jimureport
          predicates:
            - Path=/jmreport/**
          #filters:
          #  - StripPrefix=2

knife4j:
  gateway:
    enabled: true
    # 指定服务发现的模式聚合微服务文档，并且是默认`default`分组
    strategy: discover
    discover:
      enabled: true
      # 指定版本号(Swagger2|OpenAPI3)
      version : openapi3
      # 需要排除的微服务(eg:网关服务)
      excluded-services:
        - quick-boot-gateway

# 忽略认证的地址
ignore:
  url:
    - /favicon.ico
    - /doc.html
    - /api/system/v3/api-docs/**
    - /api/auth/v3/api-docs/**
    - /webjars/**
    - /swagger-resources/**
    - /v3/api-docs/**
    - /actuator/**
    - /instances/**
    - /api/system/menu/getRoutes
    - /api/auth/doLogin
    - /api/auth/oauth2/**
    - /jmreport/**
    - /api/system/tenant/list