server:
  port: 8084

spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: ${mysql-server.address}/quick-boot-flow?${mysql-server.params}
          username: ${mysql-server.username}
          password: ${mysql-server.password}
          driver-class-name: ${mysql-server.driver-class-name}

# warm-flow工作流配置
warm-flow:
  # 是否显示banner图，默认是
  banner: true
  # 填充器 （可配置文件注入，也可用@Bean/@Component方式）
  data-fill-handler-path: com.quick.flow.handler.FlowDataFillHandler
  # 全局租户处理器（可配置文件注入，也可用@Bean/@Component方式）
  tenant_handler_path: com.quick.flow.handler.FlowTenantHandler
  # 是否开启逻辑删除
  logic_delete: true
  # 逻辑删除字段值（开启后默认为2）
  logic_delete_value: 1
  # 逻辑未删除字段（开启后默认为0）
  logic_not_delete_value: 0